# Generated by Django 5.0.7 on 2024-07-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teach_Email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teach_Lname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teach_Pass',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teach_Rname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teach_Uname',
        ),
    ]
