# Generated by Django 5.0.7 on 2024-07-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_teacher_teach_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Stu_Image',
        ),
    ]
