# Generated by Django 5.0.7 on 2024-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_stu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Stu_Rname',
            new_name='Stu_Course',
        ),
        migrations.AddField(
            model_name='student',
            name='Stu_Fname',
            field=models.CharField(default='Null', max_length=250),
            preserve_default=False,
        ),
    ]
