# Generated by Django 5.0.7 on 2024-07-26 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_stu_rname_student_stu_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Stu_Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses'),
        ),
    ]
